### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Hadeelalhaj** [spd-master-web/SPD_ecommerce#1]
Hi!
as for the Search bar : we need to achieve the design as per the attached img.
1- we couldn't delete the buttons and replace them with the new categories
2- we need to add a search field for the search icon in the home page 
3- As we were changing the input filed  to the new text it changed the font style. 

This is the link for the website :

https://www.sunglasshut.com/webapp/wcs/stores/servlet/AjaxOrderItemDisplayView?catalogId=20602&langId=-1&storeId=10152&krypto=trv9QYBQN53HpOmeRDq4GzKEq3kue6850zsY3Hr3OIOuZF5cw86lz66tKJgyl445QvaTJilz95GeX5HR1x0ffmDars%2BHRaUHCQ85yLWjDF9GgjnMvvjXhVLihEFLad4mkDO1PU0yq%2BpUUUiMJvwgOO3GPJM8UkiHhQekYHN3l%2BlejR%2Bbe0GCl4XO%2F0oQPDWP&ddkey=https%3AOrderCalculate

**Comment by RujutaP21** [comment]
@gorazd 

As discussed, issue on search of sunglasses hut website: https://www.sunglasshut.com/us 
Adding two h2 with class element in the div class (sgh-search-suggestions)

Final output requirement: images/search_bar_after.PNG

Other changes:
https://github.com/spd-master-web/Snow-E-commerce-Design/blob/6131692c01fe7cc42a139fee77072a006ab2275f/index.html#L84

**Comment by gorazd** [comment]
I'll attach an example, let me know if it solves your problem:
[jquery.html.zip](https://github.com/spd-master-web/Snow-E-commerce-Design/files/4786040/jquery.html.zip)

**Comment by RujutaP21** [comment]
It worked
