### ISSUE TITLE
Change cursor hover icon in PDP 

### ISSUE THREAD

**Issue by Hadeelalhaj** [spd-master-web/SPD_ecommerce#2]
Hello, 
In  sunglass hut : https://www.sunglasshut.com/us/versace/ve2219b-8056597160414

1- when hover over the product, the cursor  will change to icon " search / magnifier"
2- we want to change the icon
3- we found the pice of code that changed the icon, but it just change it when you are on the main img  if you changed the view it's not gonna apply. 
4-the code is provided in html from line 113

**Comment by gorazd** [comment]
What do you mean it changes when you change the view?

The code at line 113 is this:

```
setData: function(dataname, datavalue) {
  var srcdata = this.getDataLayer();
  srcdata[dataname] = datavalue;
  },
```
